# Generated by Django 5.0 on 2026-09-16 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_propios', to=settings.AUTH_USER_MODEL)),
                ('ultimo_editor', models.ForeignKey(blank=True, help_text='Último usuario que modificó el contenido del documento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_editados_ultimo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-actualizado'],
            },
        ),
        migrations.CreateModel(
            name='VersionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='editor.documento')),
                ('usuario', models.ForeignKey(help_text='Usuario que guardó esta versión', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Versión de Documento',
                'verbose_name_plural': 'Versiones de Documentos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PermisoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_editar', models.BooleanField(default=False)),
                ('fecha_compartido', models.DateTimeField(auto_now_add=True)),
                ('compartido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_otorgados', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='editor.documento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_compartidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso de Documento',
                'verbose_name_plural': 'Permisos de Documentos',
                'ordering': ['-fecha_compartido'],
                'unique_together': {('documento', 'usuario')},
            },
        ),
    ]
